### PR TITLE
Add reference id parameter align the business with the iOS SDK

### PR DESCRIPTION
**Pull request by citcon-aoyansheng**
## Jira Ticket
[Jira Ticket]()

## What are you trying to accomplish?
Add reference id parameter align the business with the iOS SDK
## How did you accomplish this?
Add a reference_id parameter

## Visual:

| Before | After |
|--------|-------|
|        |       |

### CODE REVIEW

**Comment by pedronveloso** [comment]
Hi,

Thank you for the PR and bringing this issue to our attention. We ended up doing a separate PR to address the issue, as the parameter did already exist but wasn't being correctly used by the network layer.

This is the corresponding parameter you should use: https://github.com/cashapp/cash-app-pay-android-sdk/blob/main/core/src/main/java/app/cash/paykit/core/models/sdk/CashAppPayPaymentAction.kt#L53

It is only available for on-file transactions, and that's as expected. We just released version `2.4.0` of the SDK which fixes the underlaying cause of the issue.

I'm going to close this PR as a result. Feel free to tag me if you need further assistance.

**Comment by citcon-aoyansheng** [comment]
Thx @pedronveloso. I noticed the new release 2.4.0 you just published, but we currently use both on-file and one-time modes. For the one-time mode, how do we set the reference_id parameter? The [Web API](https://developers.cash.app/docs/api/customer-request-api/operations/create-a-request#request-body) and [iOS SDK](https://github.com/cashapp/cash-app-pay-ios-sdk/blob/8e9b575a6bb0d0671762b06ed7a0938c66680add/Sources/PayKit/CustomerRequest.swift#L24C1-L25C1) currently have good support for this parameter.

Here is my sample code: 

image

image

**Comment by pedronveloso** [comment]
It was a mix up on my end. There is indeed a parameter which is unique to on-file payments, called `account_reference_id` , same as in our iOS and API: https://github.com/cashapp/cash-app-pay-ios-sdk/blob/8e9b575a6bb0d0671762b06ed7a0938c66680add/Sources/PayKit/CustomerRequest.swift#L203

But what you want/need is the top-level `reference_id`, which should be available for both payment types. I'm working on a fix, and will let you know once we've deployed a new version.

**Comment by citcon-aoyansheng** [comment]
@pedronveloso Thank you very much. 👍

**Comment by pedronveloso** [comment]
> @pedronveloso Thank you very much. 👍

Thanks for understanding. Should be all good now on `2.5.0` : https://github.com/cashapp/cash-app-pay-android-sdk/releases/tag/v2.5.0

**Pull request closed without merging**
